apiVersion: apps/v1
kind: Deployment
metadata:
  name: sockperf-udp
  labels:
{{ include "netperf.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netperf.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "netperf.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: sockperf
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: sockperf
              containerPort: {{ .Values.config.sockperf.udp.port }}
              protocol: UDP
          command: ["/usr/bin/sockperf", "server", "-p", "{{ .Values.config.sockperf.udp.port }}"]
